### ISSUE TITLE
Не работает сохранение расписания вообще

### ISSUE THREAD

**Issue by rezunenko** [isqua/asocial#67]
консоль выводит ошибку при вводе с любыми комбинациями:
Error in response to storage.get: TypeError: Cannot read property 'days' of null
    at TableController.row (chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:656:64)
    at TableController.table (chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:678:58)
    at Object.chrome.storage.sync.get.obj [as callback] (chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:91:26)
    at window.addEventListener (chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:88:26)

**Comment by fyvfyv** [comment]
@rezunenko А какая версия браузера? В какой момент появились ошибки? Что-то добавляли/удаляли/изменяли перед их появлением?

**Comment by rezunenko** [comment]
Сначала возникла проблема с тем, что время не хотело учитывать и ставило весь день, вне зависимости от вводимых диапазонов времени. 
Пробовал различные форматы:
9 -  19
9:00    -   19:00 
09:00  -   19:00
09-00  -  19-00

И так далее. Сохранение происходило, но время не проставлялось(блокировало на весь день). 
Потом уже в одну из следующих попыток вообще перестало сохранять. При нажатии на "добавить" ничего не происходит. Если поглядеть в консоль, то можно увидеть ошибки:

options.html:1 Error in response to storage.get: TypeError: Cannot read property 'days' of null
    at TableController.row (chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:656:64)
    at TableController.table (chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:678:58)
    at Object.chrome.storage.sync.get.obj [as callback] (chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:91:26)
    at window.addEventListener (chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:88:26)
options.html:1 Unchecked runtime.lastError while running storage.set: QUOTA_BYTES_PER_ITEM quota exceeded
    at Rules.add (chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:551:26)
    at FormManager.on (chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:62:49)
    at chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:437:14
    at FormManager.EventEmitter.trigger (chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:436:31)
    at HTMLButtonElement.FormManager.addButton.addEventListener (chrome-extension://cddphjncbagpiodhpbfnkfmhcckkepeg/options/options.js:286:19)

Версия браузера: Chrome 58.0.3029.110 (64-bit)

**Comment by rezunenko** [comment]
Уточню еще, что уже при открытии плагина возникает первая ошибка в консоли:
options.html:1 Error in response to storage.get: TypeError: Cannot read property 'days' of null
at TableController.row

Вторая возникает уже при нажатии на кнопку "добавить"
